In [1]:
import torch
torch.__version__

'2.5.1+cpu'

In [2]:
scalar = torch.tensor(42)

In [3]:
scalar

tensor(42)

In [4]:
scalar.ndim

0

In [ ]:
vector = torch.tensor([7])
vector

tensor([7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([1])

In [ ]:
matrix = torch.tensor([[1,2],[4,5]])
matrix

tensor([[1, 2],
        [4, 5]])

In [ ]:
tensor=torch.tensor([[[1,2,3],[3,4,5],[7,8,6]]])

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor.ndim

3

In [ ]:
tensor1=torch.tensor([[[1,2,3],[3,4,5]]])

In [ ]:
tensor1.shape

torch.Size([1, 2, 3])

In [ ]:
tensor1.ndim

3

In [ ]:
random=torch.rand(3,4)
random

tensor([[0.2666, 0.6274, 0.2696, 0.4414],
        [0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062]])

In [ ]:
random1=torch.rand(1,2,3)
random1

tensor([[[0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090]]])

In [ ]:
zeros = torch.zeros(size=(1,2,3))
zeros


tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
ones = torch.ones(size=(1,2,3))
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
A = torch.arange(2,44,5)
A

tensor([ 2,  7, 12, 17, 22, 27, 32, 37, 42])

In [ ]:
f16=torch.tensor([1,2,3],
                dtype=torch.float16)

In [ ]:
f16

tensor([1., 2., 3.], dtype=torch.float16)

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
tensor2=torch.tensor([1,2,3])
tensor2

tensor([1, 2, 3])

In [ ]:
tensor2.ndim

1

In [ ]:
tensor2.shape

torch.Size([3])

In [ ]:
print(tensor2 + 10)
print(tensor2*10)

tensor([11, 12, 13])
tensor([10, 20, 30])


In [ ]:
print(tensor2*tensor2)
print(torch.matmul(tensor,tensor))

tensor([1, 4, 9])
tensor([[[28, 34, 31],
         [50, 62, 59],
         [73, 94, 97]]])


In [ ]:
a=torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float32)

b=torch.tensor([[7,10],[8,10],[9,12]],dtype=torch.float32)

In [ ]:
torch.matmul(a.T,b)

tensor([[ 76., 100.],
        [100., 132.]])

In [ ]:
torch.manual_seed(42)

In [ ]:
linear=torch.nn.Linear(in_features=2,out_features=6)
x=a
out=linear(x)
out


tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

In [ ]:
out.shape

torch.Size([3, 6])

In [ ]:
x.shape

torch.Size([3, 2])

In [ ]:
y = w*x.T + b,
x=[3,2]
w=[2,6]

NameError: name 'w' is not defined

In [ ]:
tensor1=torch.tensor([[1,2],[2,3],[3,4]])
tensor1

tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [ ]:
tensor1.ndim,tensor1.shape,tensor1.device

(2, torch.Size([3, 2]), device(type='cpu'))

In [ ]:
device = 'cuda' if torch.cuda.is_available else 'cpu'
device

'cuda'

In [ ]:
tensor1.to(device=device)
tensor1.device

device(type='cpu')

In [ ]:
tensor1 = tensor1.to(device = device)
tensor1.device

device(type='cuda', index=0)

In [ ]:
l1=torch.nn.Linear(in_features=3,out_features=3)
l2=torch.nn.Linear(in_features=3,out_features=1)
t=torch.rand(size=(2,3))
t

tensor([[0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423]])

In [ ]:
t.shape

torch.Size([2, 3])

In [ ]:
x=t
out = l1(x)
out= l2(out)
out

tensor([[-0.6422],
        [-0.7426]], grad_fn=<AddmmBackward0>)

In [ ]:
l1.weight,l2.weight,l1.bias,l2.bias

(Parameter containing:
 tensor([[-0.2695,  0.1472, -0.2660],
         [-0.0677, -0.2345,  0.3830],
         [-0.4557, -0.2662, -0.1630]], requires_grad=True),
 Parameter containing:
 tensor([[ 0.5214, -0.4904,  0.4457]], requires_grad=True),
 Parameter containing:
 tensor([-0.3471,  0.0545, -0.5702], requires_grad=True),
 Parameter containing:
 tensor([0.0961], requires_grad=True))

In [ ]:
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(x.min(),x.max(),x.type(torch.float32).mean())
print(x.sum,x.argmax(),x.argmin())
tensor_int8 = x.type(torch.int8)
tensor_int8

tensor(0) tensor(90) tensor(45.)
<built-in method sum of Tensor object at 0x7b39041c57b0> tensor(9) tensor(0)


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

torch.Size([1, 3, 3])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0][2]

tensor(3)

In [ ]:
x[:,1]

tensor([[4, 5, 6]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
x[:,0,0]

tensor([1])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[:,2]

tensor([[7, 8, 9]])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
x[:],x[:].shape,x[0],x[0].shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
x[:,2,1]

tensor([8])

In [ ]:
x[:,2],x[:,2].shape

(tensor([[7, 8, 9]]), torch.Size([1, 3]))

In [ ]:
x[:,0,:],x[:,0,:].shape

(tensor([[1, 2, 3]]), torch.Size([1, 3]))

In [ ]:
x[:,0],x[:,0].shape

(tensor([[1, 2, 3]]), torch.Size([1, 3]))

In [ ]:
x[:,:],x[:,:].shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0,:,0],x[:,:,0].shape

(tensor([1, 4, 7]), torch.Size([1, 3]))

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:],x[:].shape,x[0],x[0].shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
x[:,1],x[:,1].shape,x[0,1],x[0,1].shape

(tensor([[4, 5, 6]]), torch.Size([1, 3]), tensor([4, 5, 6]), torch.Size([3]))

In [ ]:
x[:,1,0],x[:,1,0].shape,x[0,1,0],x[0,1,0].shape

(tensor([4]), torch.Size([1]), tensor(4), torch.Size([]))

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[:,:,0],x[:,:,0].shape,x[0,:,0],x[0,:,0].shape

(tensor([[1, 4, 7]]), torch.Size([1, 3]), tensor([1, 4, 7]), torch.Size([3]))

In [ ]:
x[:,0,0],x[:,0,0].shape,x[0,:,0],x[0,:,0].shape

(tensor([1]), torch.Size([1]), tensor([1, 4, 7]), torch.Size([3]))

In [ ]:
x[:,0,:],x[:,0,:].shape,x[0,0,:],x[0,0,:].shape

(tensor([[1, 2, 3]]), torch.Size([1, 3]), tensor([1, 2, 3]), torch.Size([3]))

In [ ]:
import torch
x = torch.arange(1,17).reshape(1,4,4)
x,x.shape

(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16]]]),
 torch.Size([1, 4, 4]))

(tensor([[ 1,  5,  9, 13]]),
 torch.Size([1, 4]),
 tensor([ 1,  5,  9, 13]),
 torch.Size([4]))

In [ ]:
x[:,0,0],x[:,0,0].shape,x[0,0,0],x[0,0,0].shape

(tensor([1]), torch.Size([1]), tensor(1), torch.Size([]))

In [ ]:
x[:,:,0],x[:,:,0].shape,x[0,:,0],x[0,:,0].shape

(tensor([[ 1,  5,  9, 13]]),
 torch.Size([1, 4]),
 tensor([ 1,  5,  9, 13]),
 torch.Size([4]))

In [ ]:
x[:,:,0,2],x[:,:,0,2].shape,x[0,:,0,2],x[0,:,0,2].shape

IndexError: too many indices for tensor of dimension 3

In [ ]:
x[:,2,0],x[:,2,0].shape,x[0,2,0],x[0,2,0].shape

(tensor([9]), torch.Size([1]), tensor(9), torch.Size([]))

In [ ]:
import torch
x = torch.arange(1,19).reshape(2,3,3)
x,x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [ ]:
x[:,:,0,0],x[:,:,0,0].shape,x[0,:,0,0],x[0,:,0,0].shape

IndexError: too many indices for tensor of dimension 3

In [ ]:
x[:],x[:].shape,x[0],x[0].shape

(tensor([[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]),
 torch.Size([3, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
x[:,1,1],x[:,1,1].shape,x[1,1,1],x[1,1,1].shape

(tensor([ 5, 14]), torch.Size([2]), tensor(14), torch.Size([]))

In [ ]:
x[:,:,1],x[:,:,1].shape,x[1,:,1],x[1,:,1].shape

(tensor([[ 2,  5,  8],
         [11, 14, 17]]),
 torch.Size([2, 3]),
 tensor([11, 14, 17]),
 torch.Size([3]))

In [3]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [6]:
z=x.view(-1)
z,x

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [7]:
224*224*3

150528

In [9]:
img = torch.rand(size=(224,224,3))
img2 = img.view(-1)
img2.shape


torch.Size([150528])

In [12]:
a=torch.arange(1,10)
b = torch.stack([a,a,a,a], dim = 0)
b

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
a=torch.arange(1,10)
b = torch.stack([a,a,a,a], dim = 1)
b

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [14]:
c=torch.rand(1,2,2,3,1,6)

In [15]:
c.ndim

6

In [29]:
sq=c.squeeze(dim=4)
sq

tensor([[[[[0.8896, 0.1907, 0.8062, 0.9344, 0.9622, 0.2117],
           [0.8206, 0.1923, 0.5928, 0.2453, 0.9870, 0.3540],
           [0.0207, 0.7429, 0.5957, 0.7020, 0.2463, 0.4775]],

          [[0.1519, 0.0686, 0.1575, 0.8677, 0.4218, 0.3941],
           [0.1520, 0.4319, 0.5089, 0.8718, 0.6053, 0.7916],
           [0.4124, 0.0139, 0.9827, 0.6069, 0.9137, 0.6061]]],


         [[[0.8980, 0.4999, 0.8651, 0.9767, 0.3455, 0.1256],
           [0.6158, 0.0228, 0.2711, 0.8787, 0.7683, 0.9273],
           [0.7749, 0.5706, 0.5237, 0.6788, 0.6576, 0.3667]],

          [[0.2447, 0.0861, 0.5377, 0.5978, 0.5368, 0.0582],
           [0.7490, 0.6418, 0.8974, 0.4578, 0.7897, 0.6208],
           [0.0784, 0.9486, 0.0445, 0.6779, 0.1514, 0.7927]]]]])

In [30]:
sq.shape

torch.Size([1, 2, 2, 3, 6])

In [33]:
sq=sq.unsqueeze(dim=2)
sq

tensor([[[[[[0.8896, 0.1907, 0.8062, 0.9344, 0.9622, 0.2117],
            [0.8206, 0.1923, 0.5928, 0.2453, 0.9870, 0.3540],
            [0.0207, 0.7429, 0.5957, 0.7020, 0.2463, 0.4775]],

           [[0.1519, 0.0686, 0.1575, 0.8677, 0.4218, 0.3941],
            [0.1520, 0.4319, 0.5089, 0.8718, 0.6053, 0.7916],
            [0.4124, 0.0139, 0.9827, 0.6069, 0.9137, 0.6061]]]],



         [[[[0.8980, 0.4999, 0.8651, 0.9767, 0.3455, 0.1256],
            [0.6158, 0.0228, 0.2711, 0.8787, 0.7683, 0.9273],
            [0.7749, 0.5706, 0.5237, 0.6788, 0.6576, 0.3667]],

           [[0.2447, 0.0861, 0.5377, 0.5978, 0.5368, 0.0582],
            [0.7490, 0.6418, 0.8974, 0.4578, 0.7897, 0.6208],
            [0.0784, 0.9486, 0.0445, 0.6779, 0.1514, 0.7927]]]]]])

In [34]:
sq.shape

torch.Size([1, 2, 1, 2, 3, 6])

In [35]:
d= torch.arange(1,10)
d

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
dsq=d.unsqueeze(dim=1)
dsq

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [37]:
img = torch.rand(224,224,3)#h,w,co

In [40]:
pimg=img.permute(2,0,1)
#3,224,224
#co,h,w

In [45]:
import numpy as np
array= np.arange(1.,8.)
tensor = torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [46]:
array.dtype,tensor.dtype

(dtype('float64'), torch.float32)

In [47]:
t=torch.arange(1,10)
t

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr=tensor.numpy().astype(np.float64)
arr,arr.dtype

(array([1., 2., 3., 4., 5., 6., 7.]), dtype('float64'))